bdd_med/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog

from rest_framework import routers

from .admin import admin_site

import media.views
import users.views

# API router
router = routers.DefaultRouter()
router.register(r'media/author', media.views.AuthorViewSet)
router.register(r'media/borrowable', media.views.BorrowablePolymorphicViewSet)
router.register(r'media/comic', media.views.ComicViewSet)
router.register(r'media/manga', media.views.MangaViewSet)
router.register(r'media/novel', media.views.NovelViewSet)
router.register(r'media/vinyl', media.views.VinylViewSet)
router.register(r'media/cd', media.views.CDViewSet)
router.register(r'media/track', media.views.TrackViewSet)
router.register(r'media/review', media.views.ReviewViewSet)
router.register(r'media/game', media.views.GameViewSet)
router.register(r'media/borrow', media.views.BorrowViewSet)
router.register(r'users/user', users.views.UserViewSet)
router.register(r'users/group', users.views.GroupViewSet)


urlpatterns = [
    path('', users.views.IndexView.as_view(), name='index'),
    path('admin/', admin_site.urls, name="admin"),

    path('users/', include('users.urls')),

    # Include Django Contrib and Core routers
    path('accounts/', include('django.contrib.auth.urls')),
    path('media/', include('media.urls')),

    # REST API
    path('api/', include(router.urls)),

    # JS translation
    path(
        'jsi18n/',
        cache_page(3600)(JavaScriptCatalog.as_view()),
        name='javascript-catalog'
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

media/urls.py
from django.urls import path

from . import views

app_name = 'media'
urlpatterns = [
    path('borrow/', views.NewBorrowFormView.as_view(), name="borrow"),
    path('return/', views.ReturnView.as_view(), name="return"),

    path('<int:pk>/', views.MediaDetailView.as_view(), name='detail'),
    path('add/', views.CreateBorrowableView.as_view(), name="add"),
    path('edit/<int:pk>', views.EditBorrowableView.as_view(), name="edit"),

    path('find/', views.PolymorphicListView.as_view(), name='find'),
    path('find-advanced/', views.AdvancedSearchView.as_view(),
         name='find-advanced'),

    path('mes_emprunts/', views.MyLoansListView.as_view(),
         name="mes_emprunts"),
    path('return/', views.ReturnView.as_view(), name='return'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('authorize/', views.AuthorizeView.as_view(), name='auth'),
]

bdd_med/templates/autocomplete_model.html
<div>
    <input type="hidden" name="{{ widget.name }}" {% if widget.attrs.model_pk %}value="{{ widget.attrs.model_pk }}"{% endif %} id="{{ widget.attrs.id }}_pk">
    <input type="text"
           {% if widget.value != None and widget.value != "" %}value="{{ widget.value }}"{% endif %}
           name="{{ widget.name }}_name" autocomplete="off"
           {% for name, value in widget.attrs.items %}
               {% if value != False %}{{ name }}{% if value != True %}="{{ value|stringformat:'s' }}"{% endif %}{% endif %}
           {% endfor %}
           aria-describedby="{{widget.attrs.id}}_tooltip">
    {% if widget.resetable %}
    <a id="{{ widget.attrs.id }}_reset" class="btn btn-light
                                       autocomplete-reset">Réinitialiser</a>
    {% endif %}
    <div role="tooltip" id="{{ widget.attrs.id }}_tooltip" hidden></div>
</div>

bdd_med/templates/autocomplete_multiple_model.html
<div id="{{ widget.attrs.id }}_div">
    <div class="card bg-light mb-4">
        {% if widget.title != None %}
        <div class="card-header">
            <p class="card-text font-weight-bold">
            <label for="source_note" id="{{ widget.attrs.id }}_label">
                {{ widget.title }}
            </label>
            </p>
        </div>
        {% endif %}
        <div id="{{ widget.attrs.id }}_initial" hidden>
            {% for id, name in widget.values %}
            <div value_pk="{{ id }}" value_name="{{ name }}"></div>
            {% endfor %}
        </div>
        <ul class="list-group list-group-flush" id="{{ widget.attrs.id }}_display">
        </ul>
        <div class="card-body">
            <input type="text" value=""
                   widget_name="{{ widget.name }}"
                   name="{{ widget.name }}_name" autocomplete="off"
                   {% for name, value in widget.attrs.items %}
                       {% if value is not False %}{{ name }}{% if value is not True %}="{{ value|stringformat:'s' }}"
                       {% endif %}{% endif %}
                   {% endfor %}
                   aria-describedby="{{ widget.attrs.id }}_tooltip">
            <div role="tooltip" id="{{ widget.attrs.id }}_tooltip" hidden></div>
        </div>
    </div>
</div>

bdd_med/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}{{ title }}{% endblock title %} - {{ request.site.name }}
        </title>
        <meta name="description" content="Le site de la Mediatek de l'ENS Paris-Saclay.">


        {# CSS #}
        <link rel="stylesheet" href="{% static "base.css" %}">
        <link href="{% static 'formset/css/collections.css' %}" rel="stylesheet">
        <script type="module" src="{% static 'formset/js/django-formset.js' %}"></script>
        <script src="{% url 'javascript-catalog' %}"></script>
        {% if form.media %}
            {{ form.media }}
        {% endif %}

        {% block extracss %}{% endblock %}
    </head>
    <body>
        <main>
            <nav class="navbar">
                <ul class="navbar">
                    <li class="nav-item nav-item-site">
                        <a class="nav-link" href="/">Mediatek : {{ request.site.name }}</a>
                    </li>
                    <li class="nav-item"> {# TODO permissions ? #}
                        <a class="nav-link" href="{% url "media:find" %}">Rechercher</a>
                    </li>
                    <li class="nav-item"> {# TODO permissions ? #}
                        <a class="nav-link"
                            href="{% url "media:find-advanced" %}">
                            Recherche avancée
                        </a>
                    </li>
                    {% if user.is_authenticated %} {# TODO permissions #}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "media:add" %}">
                                Nouveau média
                            </a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %} {# TODO permissions #}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "media:borrow" %}">
                                Emprunter
                            </a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %} {# TODO permissions #}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "media:return" %}">
                                Retour d'emprunts
                            </a>
                        </li>
                    {% endif %}
                    {% if user.is_superuser %} {# TODO c'est is_staff #}
                        <li class="nav-item">
                            <a class="nav-link" href="/admin">Admin</a>
                        </li>
                    {% endif %}


                    {% if user.is_authenticated %}
                    {# TODO : pouvoir voir ses emprunts ? #}
                        <li class="nav-item nav-item-login">
                            <a class="nav-link" href="{% url "media:mes_emprunts" %}">Mes emprunts</a>
                        </li>
                    {% endif %}
                    <li class="nav-item nav-item-login">
                        {% if user.is_authenticated %}
                             <a class="nav-link" href="{% url "users:logout" %}">Se déconnecter</a>
                        {% else %}
                             <a class="nav-link" href="{% url "users:login" %}">Se connecter</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
            {% block content %}
            <p>Default content...</p>
            {% endblock %}
        </main>
        <footer>
        </footer>
        {% block extrajavascript %}{% endblock %}
    </body>
</html>